spring:
  application:
    name: araraflyapi

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

neuralnetwork:
  host: ${NEURAL_NETWORK_HOST}
  model: ${NEURAL_NETWORK_MODEL}
  token: ${NEURAL_NETWORK_TOKEN}

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

docker:
  host: ${DOCKER_HOST}
  tlsVerify: false

gitea:
  admin: ${ADMIN_USERNAME}
  token: ${GITEA_TOKEN}
  url: ${URL_GITEA_API}
